RMSE - find the best fitted line

#algorithm
def product(x,w,b)
w = 0
b = 0
  y = 0
  y = x * w + b => y = mx + c
  return y
y = predict(x,b,w)
##Note:


In [3]:
import numpy as np
#Lists
x = [[1, 2], [3, 4]]
y = [2, 4, 6, 8]


for i in range(len(y)):
    result = 0
    for j in range(len(x)):
        result += sum(val * y[i] for val in x[j])
    print(result)

x_np = np.array(x)
y_np = np.array(y)
# z = x_np * y_np
# print(z)
#matrics = np.array(z)
#print(matrics)

20
40
60
80


In [5]:
import numpy as np
#Lists
x = [[1, 2], [3, 4]]
y = [[2, 4], [6, 8]]
for i in range(2):
  for j in range(2):
    a = np.array(x[i]) * np.array(y[j])
    b = np.array(x[j]) * np.array(y[i])
    print(a+b)

[ 4 16]
[12 32]
[12 32]
[36 64]


In [6]:
import numpy as np
x = [[1, 2], [3, 4]]
y = [[2, 4], [6, 8]]
z = [[0, 0], [0, 0]]

for i in range(2):
  for j in range(2):
    for k in range(2):
      z[i][j] += x[i][k] * y[k][j]
      print(z)
for row in z:
    print(row)

[[2, 0], [0, 0]]
[[14, 0], [0, 0]]
[[14, 4], [0, 0]]
[[14, 20], [0, 0]]
[[14, 20], [6, 0]]
[[14, 20], [30, 0]]
[[14, 20], [30, 12]]
[[14, 20], [30, 44]]
[14, 20]
[30, 44]


In [7]:
import pandas as pd
data = {
'x' : [1, 2, 3, 4],
'y' : [1, 3, 5, 7],
"y'" : [0, 0, 0, 0]
}
df = pd.DataFrame(data)

In [8]:
print(df)

   x  y  y'
0  1  1   0
1  2  3   0
2  3  5   0
3  4  7   0


In [9]:
import numpy as np
x = [[1, 1], [1, 2], [1, 3], [1, 4]]
#y = [2, 4, 6, 8]
theta = np.array([0, 0])
y = np.dot(x, theta)
print(y)

def regline(w, x, b):
  y = 0
  yPred = x * theta
  return yPred

print(df)

[0 0 0 0]
   x  y  y'
0  1  1   0
1  2  3   0
2  3  5   0
3  4  7   0


In [29]:
import pandas as pd
import numpy as np
data = {
    'x': [1, 2, 3, 4],
    'y': [3, 5, 7, 9]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
   x  y
0  1  3
1  2  5
2  3  7
3  4  9


In [30]:
theta = np.array([0, 0])
df["y'"] = theta[0] * df['x'] + theta[1]
print(df)

   x  y  y'
0  1  3   0
1  2  5   0
2  3  7   0
3  4  9   0


In [13]:
print(type(df["y'"]))

<class 'pandas.core.series.Series'>


In [31]:
theta = np.array([0, 0])
df["y'"] = theta[0] * df['x'] + theta[1]

print(df)
print(type(df["y'"]))
#X_matrix = np.column_stack([np.ones(len(df)), df['x'].values])
#theta_matrix = theta.reshape(-1, 1)
#yPred_matrix = np.dot(X_matrix, theta_matrix).flatten()

#df['yPred_matrix'] = yPred_matrix

#print("\nDataFrame with both yPred methods:")
#print(df)


   x  y  y'
0  1  3   0
1  2  5   0
2  3  7   0
3  4  9   0
<class 'pandas.core.series.Series'>


In [32]:
m = df.shape[0]
x = np.hstack((np.ones((m,1)), df.x.values.reshape(-1,1)))
print("x matrix")
x

x matrix


array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.]])

In [33]:
y = np.array(df.y.values).reshape(-1,1)
theta = np.zeros(shape=(x.shape[1],1))
print(theta)

def predict(x, theta):
  return x.dot(theta)
yPred = predict(x, theta)
print("y'")
print(yPred)

[[0.]
 [0.]]
y'
[[0.]
 [0.]
 [0.]
 [0.]]


In [34]:
print(df)
print("y matrix")
print(y)
print("y' matrix")
print(yPred)

   x  y  y'
0  1  3   0
1  2  5   0
2  3  7   0
3  4  9   0
y matrix
[[3]
 [5]
 [7]
 [9]]
y' matrix
[[0.]
 [0.]
 [0.]
 [0.]]


In [37]:
cost_func = yPred-y
print(cost_func)
print(type(cost_func))

[[-3.]
 [-5.]
 [-7.]
 [-9.]]
<class 'numpy.ndarray'>


In [53]:
cost_function = np.sum(np.square(yPred - y))
print(cost_function)

164.0


In [54]:
(1/(2*m)) * (yPred - y).T.dot(cost_func)

array([[20.5]])

In [58]:
# theta =
n = len(x)
print(n)
print(x)
gradient_descent_bias = (1/n) * np.sum(yPred - y)
print(gradient_descent_bias)
#
gradient_descent_weight = (1/n) * np.sum((cost_func)*x)
print(gradient_descent_weight)


4
[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]]
-6.0
-23.5
